# Generated by Django 3.2.16 on 2024-02-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_chartscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartscore',
            name='after_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='疫情后'),
        ),
        migrations.AlterField(
            model_name='chartscore',
            name='before_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='疫情前'),
        ),
        migrations.AlterField(
            model_name='chartscore',
            name='during_score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='疫情中'),
        ),
    ]
